volumes:
  data:
    name: blazesnowcom_data
    external: true

services:
  blazesnowcom:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest
    container_name: blazesnowcom
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - data:/data
      - ./.env:/etc/caddy/.env:ro
