volumes:
  data:
    name: blazesnowcom_data
    external: true

services:
  blazesnowcom:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest
    container_name: blazesnowcom
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - data:/data
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
