services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    depends_on:
    - mysql
    volumes:
    - ./gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 3000:3000
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - GITEA__database__DB_TYPE=mysql
    - GITEA__database__HOST=mysql:3306
    - GITEA__database__NAME=gitea
    - GITEA__database__USER=gitea
    - GITEA__database__PASSWD=gitea

  mysql:
    image: mysql:lts
    container_name: mysql
    restart: always
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=true
    - MYSQL_DATABASE=gitea
    - MYSQL_USER=gitea
    - MYSQL_PASSWORD=gitea
