services:
  nfs:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs
    privileged: true
    restart: always
    volumes:
    - ./data:/nfsshare
    ports:
    - 2049:2049
    environment:
    - SHARED_DIRECTORY=/nfsshare
    - SYNC=true
    - READ_ONLY=true
    - PERMITTED="192.168.*.*"
