services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: always
    volumes:
    - ./cache:/var/cache/ntfy
    - ./ssl:/var/ssl:ro
    - ./server.yml:/etc/ntfy/server.yml:ro
    ports:
    - 2586:2586
    environment:
    - TZ=CST
    command:
    - serve
