services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    ports:
    - 8000:8000
    - 9443:9443
    volumes:
    - ./data:/data
    command: -H tcp://agent:9001 --tlsskipverify

  agent:
    image: portainer/agent:alpine
    container_name: portainer_agent
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/volumes:/var/lib/docker/volumes
