services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: always
    volumes:
    - ./data:/data
    environment:
      SIGNUPS_ALLOWED: "true" # 允许注册新用户

  caddy:
    image: caddy:alpine
    container_name: caddy-vaultwarden
    restart: always
    depends_on:
    - vaultwarden
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
    - 80:80
    - 443:443
