volumes:
  data:
    name: example_data
    external: true

services:
  output:
    image: busybox:latest
    container_name: outputvolumes
    restart: no
    volumes:
    - data:/data:ro
    - ./:/app
    command: tar -czf /app/data.tar.gz -C / data

  input:
    image: busybox:latest
    container_name: inputvolumes
    restart: no
    volumes:
    - data:/data
    - ./:/app:ro
    command: tar -xzf /app/data.tar.gz -C / data
