services:
  webdav:
    image: bytemark/webdav:latest
    container_name: webdav
    restart: always
    ports:
    - 80:80
    environment:
      AUTH_TYPE: Digest
      USERNAME: 此处填写用户名
      PASSWORD: 此处填写密码
    volumes:
    - ./dav:/var/lib/dav
