name: 发布至阿里云Docker镜像服务

on:
  push:
    branches: [ main ]

env:
  REGISTRY: "${{ vars.REGISTRY }}"
  USERNAME: "${{ vars.USERNAME }}"
  TOKEN: "${{ secrets.TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in
      run: docker login -u $USERNAME -p $TOKEN $REGISTRY

    - name: Build
      run: docker build -t registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest .

    - name: Push
      run: docker push registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest
