name: Docker Publish
description: Publish Docker image to Alibaba Cloud Container Registry

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: BlazeSnow23
        password: ${{ secrets.TOKEN }}
        logout: true

    - name: Build
      run: docker build -t registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest .

    - name: Push
      run: docker push registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest
