name: Docker Dev
description: Build and push Docker image for development

on:
  workflow_dispatch:


jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: BlazeSnow23
        password: ${{ secrets.TOKEN }}
        logout: true

    - name: Build
      run: docker build -t registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:dev .

    - name: Push
      run: docker push registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:dev
