name: 发布至阿里云Docker镜像服务

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build
      run: docker build -t registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest .

    - name: Push
      run: docker push registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest
