name: Docker Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Log in
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: BlazeSnow23
        password: ${{ secrets.TOKEN }}
        logout: true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: npm

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install dependencies
      run: npm ci

    - name: Build with VitePress
      run: npm run docs:build

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest
