name: 部署至GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检查代码
      uses: actions/checkout@v4
    - name: 安装Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: 检查GitHub Pages
      uses: actions/configure-pages@v5
    - name: 安装依赖
      run: npm install
    - name: 构建网站
      run: npm run docs:build
    - name: 上传构建
      uses: actions/upload-pages-artifact@v3
      with:
        path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 部署至GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
