name: Publish BlazeSnow Site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Build with VitePress
      run: npm run docs:build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: blazesnow
        path: .vitepress/dist

  publish-github:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: blazesnow
        path: .vitepress/dist

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: .vitepress/dist

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

  publish-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: blazesnow
        path: .vitepress/dist

    - name: Login to Alibaba Cloud
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: BlazeSnow23
        password: ${{ secrets.AlibabaTOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: blazesnow
        password: ${{ secrets.TOKEN }}

    - name: Login to GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          registry.cn-hangzhou.aliyuncs.com/blazesnow/blazesnowcom:latest
          blazesnow/blazesnowcom:latest
          ghcr.io/blazesnow/blazesnowcom:latest
