name: Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v2026.3.31.0'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        lfs: true

    - name: Run ReleaseZip
      uses: BlazeSnow/ReleaseZip@main
      with:
        artifact_name: ${{ github.event.repository.name }}-${{ inputs.tag }}
        retention_days: 7

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.tag }}
